//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVCEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class İlac
    {
        public int ID { get; set; }
        public string IlacAd { get; set; }
        public string IlacSirketi { get; set; }
        public string IlacTuru { get; set; }
        public Nullable<int> IlacKutuAdet { get; set; }
    }
}
