//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVCEczane.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EczaneEntities2 : DbContext
    {
        public EczaneEntities2()
            : base("name=EczaneEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<İlac> İlac { get; set; }
        public virtual DbSet<Kullanicilar1> Kullanicilar1 { get; set; }
        public virtual DbSet<Sipari> Siparis { get; set; }
        public virtual DbSet<Stok> Stoks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
