//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVCEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipari
    {
        public int SiparişID { get; set; }
        public Nullable<int> SiparisAdet { get; set; }
        public string GelisTarihi { get; set; }
        public string SiparisTarihi { get; set; }
    }
}
