//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVCEczane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        public int StokID { get; set; }
        public Nullable<int> StokAdet { get; set; }
        public Nullable<int> MaxGereken { get; set; }
        public Nullable<int> MinGereken { get; set; }
    }
}
